version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./test-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - socket-pulser

  relay:
    image: relay
    container_name: relay
    build:
      context: .
      dockerfile: ./relay.dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - socket-pulser

  socket-pulser:
    container_name: socket-pulser
    image: socket-pulser
    build:
      context: .
      dockerfile: ./socket-pulser.dockerfile
    ports:
      - "8081:8081"

networks:
  default:
